baseURL = 'https://rivaus.github.io'
languageCode = 'fr'
defaultContentLanguage = 'fr'
title = 'Quentin Tran'
theme = 'terminal'

tags = ['rust', 'C#', 'unity', 'learn', 'programming', 'book', 'game']

pagination.pagerSize = 8

summaryLength = 0

# Required for Chroma and the custom syntax highlighting.
# [markup.highlight]
    noClasses = false

[params]
    # dir name of your main content (default is `content/posts`).
    # the list of set content will show up on your index page (baseurl).
    # contentTypeName = "posts"

    # if you set this to 0, only submenu trigger will be visible
    showMenuItems = 2

    # show selector to switch language
    #showLanguageSelector = true

    # set theme to full screen width
    fullWidthTheme = false

    # center theme with default width
    centerTheme = true

    # if your resource directory contains an image called `cover.(jpg|png|webp)`,
    # then the file will be used as a cover automatically.
    # With this option you don't have to put the `cover` param in a front-matter.
    autoCover = true

    # set post to show the last updated
    # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
    showLastUpdated = false

    # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
    # updatedDatePrefix = "Updated"

    # whether to show a page's estimated reading time
    readingTime = true # default

    # whether to show a table of contents
    # can be overridden in a page's front-matter
    # Toc = false # default

    # set title for the table of contents
    # can be overridden in a page's front-matter
    # TocTitle = "Table of Contents" # default

    # Set date/time format for posts
    # This will impact the date/time displayed on
    # index.html, the posts list page, and on posts themselves
    # This value can also be configured per-post on front matter
    # If you have any issues with the timezone rendering differently
    # than you expected, please ensure your timezone is correctly set
    # on your server.
    # This value can be customized according to Hugo documentation:
    # https://gohugo.io/functions/time/format/
    # Default value (no changes needed):
    # dateFormat = "2006-01-02"
    # Example format, with date, time, and timezone abbreviation:
    # dateFormat = "2006-01-02 3:04:06 PM MST"

[params.giscus]
    enable = true
    repo = "Rivaus/rivaus.github.io"
    repoId = "R_kgDOQ_9BWw"
    category = "General"
    categoryId = "DIC_kwDOQ_9BW84C1py8"
    lazyLoading = false
    theme = "transparent_dark"

[languages]
    # [languages.en]
    #     languageName = "English"
    #     contentDir = 'content/en'
    #     title = "Quentin Tran"

    #     [languages.en.params]
    #         subtitle = "A simple, retro theme for Hugo"
    #         owner = ""
    #         keywords = ""
    #         copyright = "Quentin Tran"
    #         menuMore = "Show more"
    #         readMore = "Read more"
    #         readOtherPosts = "Read other posts"
    #         newerPosts = "Newer posts"
    #         olderPosts = "Older posts"
    #         missingContentMessage = "Page not found..."
    #         missingBackButtonLabel = "Back to home page"
    #         minuteReadingTime = "min read"
    #         words = "words"

    #     [languages.en.params.logo]
    #         logoText = "Quentin Tran"
    #         logoHomeLink = "/"

    #     [languages.en.menu]
    #         [[languages.en.menu.main]]
    #             identifier = "guides"
    #             name = "Guides"
    #             url = "/guides"
    #         [[languages.en.menu.main]]
    #             identifier = "about"
    #             name = "About"
    #             url = "/about"

    [languages.fr]
        languageName = "Français"
        contentDir = 'content/fr'
        title = "Quentin Tran"

        [languages.fr.params]
            subtitle = "A simple, retro theme for Hugo"
            owner = ""
            keywords = ""
            copyright = "Quentin Tran"
            menuMore = "Voir plus"
            readMore = "Lire plus"
            readOtherPosts = "Lire les autres articles"
            newerPosts = "Articles récents"
            olderPosts = "Anciens articles"
            missingContentMessage = "Page non trouvée..."
            missingBackButtonLabel = "Retour à l'accueil"
            minuteReadingTime = "minutes de lecture"
            words = "mots"

            [languages.fr.params.logo]
                logoText = "Quentin Tran"
                logoHomeLink = "/"

            [languages.fr.menu]
                [[languages.fr.menu.main]]
                    identifier = "a-propos"
                    name = "A propos"
                    url = "/about"
                [[languages.fr.menu.main]]
                    identifier = "guides"
                    name = "Guides"
                    url = "/guides"
